#!/usr/bin/env bash
# block-generated-writes.sh: PreToolUse guard that refuses agent writes to generated files.
#
# Generated files are rewritten by their generator, so a hand edit is lost or
# drifts from the source. Guarded paths:
#   - frontend/src/routeTree.gen.ts (TanStack Router plugin)
#   - frontend/src/api/generated/** (Orval)
#   - openapi/openapi.yaml (springdoc through exportOpenApi)
#
# Contract: read the harness PreToolUse JSON on stdin, print a reason to
# stderr and exit 2 to REFUSE, exit 0 to ALLOW.
# Only write-like tools are judged (tool name contains write, replace, append,
# delete, edit, or create); reads always pass.
#
# Fail-open: no stdin, invalid JSON, missing jq, or no path field ALLOWS.
#
# ponytail: the guarded paths live only in this script. `..` segments are not
# normalized, and shell redirections bypass this hook. CI `task fe-route-tree-check`,
# `task api-client-check`, and `task be-openapi-check` are the final net.

set -u

payload="$(cat 2>/dev/null || true)"
[ -n "$payload" ] || exit 0
command -v jq >/dev/null 2>&1 || exit 0

# Lowercase with tr, not ${var,,}: macOS ships bash 3.2, where ${var,,} is a
# syntax error and the hook would fail without blocking.
tool_name="$(printf '%s' "$payload" | jq -r '.tool_name // empty' 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)"
case "$tool_name" in
  *write* | *replace* | *append* | *delete* | *edit* | *create*) ;;
  *) exit 0 ;;
esac

path="$(printf '%s' "$payload" | jq -r '.tool_input.path // .tool_input.file_path // .tool_input.targetFile // .tool_input.filePath // empty' 2>/dev/null || true)"
path="${path#./}"

case "$path" in
  frontend/src/routeTree.gen.ts | */frontend/src/routeTree.gen.ts)
    echo "block-generated-writes: refused. $path is generated by the TanStack Router plugin. Edit the files under frontend/src/routes/ instead, then regenerate with \`cd frontend && vp build\` (or keep \`vp dev\` running)." 1>&2
    exit 2
    ;;
  frontend/src/api/generated/* | */frontend/src/api/generated/*)
    echo "block-generated-writes: refused. $path is generated by Orval. Change the OpenAPI document or the Orval config instead, then regenerate with \`task api-gen\` (or \`task api-client-gen\` when only the Orval config changed)." 1>&2
    exit 2
    ;;
  openapi/openapi.yaml | */openapi/openapi.yaml)
    echo "block-generated-writes: refused. $path is generated by springdoc through exportOpenApi. Change the controllers, DTO Javadoc, or OpenApiConfig, then regenerate with \`task api-gen\`." 1>&2
    exit 2
    ;;
esac

exit 0
