import { defineConfig } from "orval";

// コミット済みの OpenAPI 契約から API client と MSW handler を生成する（ADR-052）。
// 再生成は task api-client-gen で行い、src/api/generated を手で書き換えない。
export default defineConfig({
  api: {
    input: {
      target: "../openapi/openapi.yaml",
    },
    output: {
      target: "./src/api/generated/endpoints",
      schemas: {
        path: "./src/api/generated/models",
        splitByTags: true,
      },
      mode: "tags-split",
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      mock: {
        path: "./src/api/generated/mocks",
        indexMockFiles: true,
        generators: [{ type: "msw", useExamples: true }],
      },
      override: {
        // 非 2xx を ApiProblemError として投げる（docs/frontend/api-client-orval.md）。
        mutator: { path: "./src/api/api-fetch.ts", name: "apiFetch" },
        // info.version を上げるたびに全生成物の header が変わらないよう、版の行を出さない（ADR-052）。
        header: (info) => ["Generated by orval. Do not edit manually.", info.title ?? ""],
      },
    },
  },
});
