import { defineConfig } from "orval";

// info.version を上げるたびに全生成物の header が変わらないよう、版の行を出さない（ADR-052）。
const header = (info: { title?: string }) => [
  "Generated by orval. Do not edit manually.",
  info.title ?? "",
];

// コミット済みの OpenAPI 契約から API client と MSW handler を生成する（ADR-052）。
// 再生成は task api-client-gen で行い、src/api/generated を手で書き換えない。
export default defineConfig({
  api: {
    input: {
      target: "../openapi/openapi.yaml",
    },
    output: {
      target: "./src/api/generated/endpoints",
      schemas: {
        path: "./src/api/generated/models",
        splitByTags: true,
      },
      mode: "tags-split",
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      mock: {
        path: "./src/api/generated/mocks",
        indexMockFiles: true,
        generators: [{ type: "msw", useExamples: true }],
      },
      override: {
        // loader の preloadQuery と component の useSuspenseQuery が同じ query options を使えるよう、suspense 用を生成する（docs/frontend/routing-and-state.md）。
        query: { useSuspenseQuery: true },
        // apiFetch が 2xx 以外を投げるため、戻り値の型を成功の応答だけにする。
        fetch: { forceSuccessResponse: true },
        // 非 2xx を ApiProblemError として投げる（docs/frontend/api-client-orval.md）。
        mutator: { path: "./src/api/api-fetch.ts", name: "apiFetch" },
        // 任意の項目にも値を入れた mock にし、exactOptionalPropertyTypes の型検査を通す。
        mock: { required: true },
        header,
      },
    },
  },
  // 境界で応答を runtime に検証する Zod schema を生成する（ADR-024）。
  // clean が api の出力を消さないよう、別の directory に出す。
  apiZod: {
    input: {
      target: "../openapi/openapi.yaml",
    },
    output: {
      target: "./src/api/generated/zod",
      mode: "tags-split",
      client: "zod",
      fileExtension: ".zod.ts",
      clean: true,
      override: {
        // 入っている zod の版に生成物が左右されないよう、版を固定する。
        zod: { version: 4 },
        header,
      },
    },
  },
});
